# Generated by Django 6.0.5 on 2026-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('category', models.CharField(choices=[('kernel', 'Ядро'), ('ssh', 'SSH'), ('files', 'Файлы'), ('grub', 'GRUB'), ('pam', 'PAM/Пароли'), ('services', 'Сервисы')], max_length=10, verbose_name='Категория')),
                ('parameter_check', models.CharField(max_length=255, verbose_name='Проверяемый параметр')),
                ('command', models.CharField(max_length=255, verbose_name='Команда')),
                ('expected', models.CharField(max_length=255, verbose_name='Установленное значение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('importance', models.CharField(choices=[('critical', 'Критический'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10, verbose_name='Важность')),
            ],
        ),
    ]
