# Generated by Django 6.0.5 on 2026-06-14 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('category', models.CharField(choices=[('kernel', 'Ядро'), ('ssh', 'SSH'), ('files', 'Файлы'), ('grub', 'GRUB'), ('pam', 'PAM/Пароли'), ('services', 'Сервисы')], max_length=10, verbose_name='Категория')),
                ('parameter_check', models.CharField(max_length=255, verbose_name='Проверяемый параметр')),
                ('command', models.CharField(max_length=255, verbose_name='Команда')),
                ('expected', models.CharField(blank=True, max_length=255, null=True, verbose_name='Установленное значение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('importance', models.CharField(choices=[('critical', 'Критический'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10, verbose_name='Важность')),
            ],
        ),
        migrations.CreateModel(
            name='ScanProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_base_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checks', models.ManyToManyField(blank=True, to='web_interface.checks', verbose_name='Проверки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP-адрес')),
                ('port', models.IntegerField(default=22, verbose_name='Порт')),
                ('username', models.CharField(blank=True, max_length=25, null=True, verbose_name='Пользователь')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('total_servers', models.PositiveIntegerField(default=0)),
                ('processed_servers', models.PositiveIntegerField(default=0)),
                ('passed_total', models.PositiveIntegerField(default=0)),
                ('failed_total', models.PositiveIntegerField(default=0)),
                ('error_total', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.scanprofiles', verbose_name='Профиль')),
                ('servers', models.ManyToManyField(default='', to='web_interface.servers', verbose_name='Серверы')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('failed', 'Провал'), ('error', 'Ошибка')], max_length=20)),
                ('summary', models.JSONField(default=dict, help_text='{"passed": 0, "failed": 0, "error": 0}')),
                ('details', models.JSONField(default=list, help_text='Список проверок с результатами')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web_interface.scantask')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_interface.servers')),
            ],
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_interface.servers')),
            ],
        ),
    ]
