# Generated by Django 6.0.5 on 2026-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanprofiles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
