# Generated by Django 6.0.5 on 2026-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0002_scanprofiles_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='last_scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='last_scan_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servers',
            name='last_scan_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='last_scan_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
