# Generated by Django 6.0.5 on 2026-06-09 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_scanprofiles_delete_profiles_delete_roles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servers',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AddField(
            model_name='servers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
        migrations.AddField(
            model_name='servers',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='servers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='servers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='servers',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='servers',
            name='port',
            field=models.IntegerField(default=22, verbose_name='Порт'),
        ),
        migrations.AddField(
            model_name='servers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Пользователь'),
        ),
    ]
