# Generated by Django 6.0.5 on 2026-06-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0003_servers_last_scan_date_servers_last_scan_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scantask',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='scantask',
            name='servers',
        ),
        migrations.DeleteModel(
            name='ScanResults',
        ),
        migrations.DeleteModel(
            name='ScanTask',
        ),
    ]
