# Generated by Django 6.0.5 on 2026-06-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_interface', '0004_alter_servers_options_servers_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_interface.servers')),
            ],
        ),
    ]
